[package]
name = "nums_appchain"
version = "0.1.0"
cairo-version = "=2.9.2"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "nums_common::models::jackpot::m_Jackpot",
    "nums_common::models::config::m_Config",
    "nums_common::models::claims::m_Claims",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.2" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag="v1.1.2" }
piltover = { git = "https://github.com/keep-starknet-strange/piltover", rev = "fb9d988" }
starknet = "2.9.2"
nums_common = { path = "../common" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.1.2" }

[features]
default = []

[profile.slot]
[profile.mainnet]
[profile.sepolia]
